swagger: '2.0'
info:
  description: LPT APis
  version: 1.0.0
  title: LPT Frontend API's
basePath: /api/
tags:
  - name: Events
    description: Manage events

paths:
  /events:
    get:
      tags:
        - Category
      summary: Manage events
      description: 'Manage events with this API'
      operationId: events
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
    post:
      tags:
        - events
      summary: Create Category
      description: 'Create Category with this API'
      operationId: createCategory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: name
          type: string
          required: true  
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      security:
        - api_key: [] 

securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
